### PR TITLE
Initial, potentially incomplete packaging for Debian and derivatives

### PR DESCRIPTION
**Pull request by xtaran**
Especially the GUI stuff is not yet taken into account.

### CODE REVIEW

**Comment by sahib** [comment]
Hello @xtaran, 

finally had a bit of time to polish the gui stuff. As of 95880e31abfb4d1513aa52678643aa822005c746 it should work now out of the "box" on debian, without tinkering with the ``PYTHONPATH`` (althoug the workaround it a bit hacky).

So, the agenda to get a readily usable debian package would probably be:

- Finish the cmdline-package (missing: install of translation units)
- Package the gui as separate package.
- Merge this pull request.
- Propose on the debian mailing list?

...Thank you for your packaging efforts!

**Comment by sahib** [comment]
Hmm, I attempted to build the package in a Debian VM, with no apparent success:

```bash
~/rmlint $ scons dist
~/rmlint $ mv rmlint-2.4.4.tar.gz rmlint_2.4.4.orig.tar.gz
~/rmlint $ dpkg-buildpackage
[normal build output]
dpkg-source: error: cannot represent change to po/fr.mo: binary file contents changed
dpkg-source: error: add po/fr.mo in debian/sources/included-binaries if you want to store the modified binary the debian tarball 
[... lots of similar lines ...]
```

I guess Im missing a bit of instructions here...

**Comment by xtaran** [comment]
Use `dpkg-buildpackage -b` if you just want to build a binary package (`.deb`) and don't need a source package (`.dsc` + `.orig.tar.gz` + `.debian.tar.xz`).

**Comment by sahib** [comment]
Ah, thanks. ``dpkg-buildpackage -b`` did what I expected.

I fixed the tests errors (in 021b994ae70d2273bb66432219e159760f246240) that happened during the building (wasn't a real bug) and limited the tests to the normal ones (there are some other *torture tests* that take forever and need lots of memory).

Okay, now we have a package that seems to build through. What would be the next steps?
I guess peer review in the sponsoring process is missing? The gui might not be necessary for starters and might be added later as separate package.

**Comment by sahib** [comment]
@e7appew took another approach on packaging here:

https://mentors.debian.net/package/rmlint

He is currently looking for a sponsor @xtaran. Maybe you can help out here?
Since he has the packaging work in an own branch, I will close this PR. 
Only commit 	84b50cc was cherry picked.

**Comment by xtaran** [comment]
Hi,

I received @e7appew's mail with pleasure and was glad to see that it used my work as base. I will very likely sponsor it, but it might take a week or two since Debian's freeze for the next stable release is imminent. And since testing is already frozen for new packages, rmlint can only come to Debian 9 Stretch via backports. Accordingly other things are more urgent this week.

**Comment by sahib** [comment]
Hey @xtaran, I'm glad to here that.

**Comment by sahib** [comment]
Hey @xtaran, is there any news on that? Sorry for that repeated asking, but I'm curious. :wink:

**Pull request closed without merging**
