### PR TITLE
cmdline: don't confuse paths starting with '-' with stdin option

### PR DESCRIPTION
**Pull request by SeeSpotRun**

### CODE REVIEW

**Comment by sahib** [comment]
Looks good to me. :+1:

**Comment by sahib** [comment]
Okay, maybe not so good. The tests break pretty much every test that runs afterwards... :stuck_out_tongue: 
I will fix that

**Comment by sahib** [comment]
[Thou shalt not chdir and forget to chdir back!](https://github.com/sahib/rmlint/commit/ae4269811a85b5abb56207a2aed702efc344c543)

:smirk:

**Comment by SeeSpotRun** [comment]
Oops!
Well at least I made the effort to write a test...

**Pull request merged**
